### ISSUE TITLE
Setting value to false doesn't work

### ISSUE THREAD

**Issue by mokhosh** [Te7a-Houdini/alpinejs-devtools#13]
You can't set a value to `false`. I think it thinks we mean the string `"false"` and evaluates it as true.

**Comment by ryangjchandler** [comment]
This one might be a bit more difficult to get right. There might be some case (no example, but still needs to be considered) where you want to use the string `"false"` instead of the boolean, which makes it harder to ensure the data is always being applied correctly.

I think we could use the original data itself to determine if it is a boolean attribute, so if you have "test: true" by default and you set the value to "false" in the DevTools, it will always be assigned as a boolean.

Let me know if you have any other ideas, I'm not too sure how Vue handles this in their DevTools.

**Comment by mokhosh** [comment]
That could be more tricky since many people might take advantage of the dynamic nature of javascript's type system.

We can convert `true` and `false` to boolean values, and strings that are numeric to numbers. And also for array and object literals, maybe.
If someone wanted the string `"false"` they can put double quotes on it.

**Comment by ryangjchandler** [comment]
How does Vue handle it? Are you force to wrap it in quotes for it to be treated as a string?

**Comment by HugoDF** [comment]
The solution is to detect booleans coming into the devtools "data" pane and showing a toggle (checkbox) instead of a text input

I wanted to open this issue earlier but thought I would wait and see other people's feedback

I'm happy to have a crack at this if no one else is keen

**Comment by ryangjchandler** [comment]
> The solution is to detect booleans coming into the devtools "data" pane and showing a toggle (checkbox) instead of a text input
> 
> I wanted to open this issue earlier but thought I would wait and see other people's feedback
> 
> I'm happy to have a crack at this if no one else is keen

Yes, that's the one. How didn't we think of this!? Have a crack at it if you want :)

**Comment by HugoDF** [comment]
@ryangjchandler I'm adopting the "@Te7a-Houdini method": when in doubt, see what Vue devtools does 😂😂🤷🏼‍♀️

**Comment by Te7a-Houdini** [comment]
LOL :joy:

**Comment by ryangjchandler** [comment]
Love that, new life motto.

**Comment by mokhosh** [comment]
Very good method. I see Caleb does it all the time when building Livewire and Alpine, so why not do the same thing with dev tools.

**Comment by HugoDF** [comment]
Has been merged to master but isn't released yet.

Hopefully we can cut a 0.0.2 release soon
