### ISSUE TITLE
Does not detect components or data

### ISSUE THREAD

**Issue by StoyanDimitrov** [Te7a-Houdini/alpinejs-devtools#17]
I use the Firefox Add-on on Firefox Nightly. The alpinejs presence on the page is properly detected in the popup icon, but the components and data panes in the dev tools are empty.
The extension works on the [Invoice Generator](https://invoicegenerator.now.sh/), but does not work on the [Alpine Toolbox](https://www.alpinetoolbox.com/). Those sites are from alpinejs examples.

**Comment by Te7a-Houdini** [comment]
i checked them from chrome and same happened also . thanks for reporting that

**Comment by HugoDF** [comment]
Is it possible that Alpine.js is loaded but there are no components on the page?

**Comment by Te7a-Houdini** [comment]
@HugoDF i think it may be possible. but there are two things in my mind 

- first one is maybe there are some errors are happening in the console that prevents the extension from rendering the components

- second thing the extension should work in development mode only . but since Alpine doesn't have something that indicates wither the current environment is development or not . then the extension will keep working

**Comment by HugoDF** [comment]
Yeah I mean, there's no Dev mode for Alpine so it should work regardless

I do think there's an issue where we check for Alpine on the page, instead of checking that there are I utilised Alpine components on the page 🤷🏼‍♀️

Maybe we just need a better empty state

**Comment by Te7a-Houdini** [comment]
yes agree

**Comment by ryangjchandler** [comment]
> Yeah I mean, there's no Dev mode for Alpine so it should work regardless
> 
> I do think there's an issue where we check for Alpine on the page, instead of checking that there are initialised Alpine components on the page 🤷🏼‍♀️
> 
> Maybe we just need a better empty state

Check the DOM for an [x-data] attribute and filter based on whether that element has an __x that is not undefined (or whatever the property is called) since this will only exist if Alpine has initialised and started reactivity.

**Comment by ryangjchandler** [comment]
There is also a point here that Alpine doesn't technically have a development mode. This could be fixed with a PR to the library that adds a new property to the `window.Alpine` object like `inDevelopmentMode`. The developer could then apply a callback to determine if it is in development, whether that be just returning true when testing locally or on staging. It would then always be in production by default, so no need to mess around with compilation and `process.env.NODE_ENV` etc.

I believe the way Vue tackles it is by using non-minified output as a development build and minified as production when using the CDN / `<script>` tag approach.

**Comment by HugoDF** [comment]
Well, there's no separate builds for Dev and prod (eg. We don't have any extra logging/instrumentation) which is fine, we should just improve the initialisation check.

**Comment by ryangjchandler** [comment]
I'm wondering if the problem mentioned by OP @StoyanDimitrov sorts itself out when you close the devtools and re-open them?

**Comment by Te7a-Houdini** [comment]
@ryangjchandler 2 minutes this is a lot of time . do you have this page code

**Comment by ryangjchandler** [comment]
Just a single HTML file with one component that toggled a div.

**Comment by Te7a-Houdini** [comment]
ok cool i thought you were loading a huge json component

**Comment by ryangjchandler** [comment]
No, haven't even tried that yet - would be a good performance test

**Comment by HugoDF** [comment]
Had another look at this, the error is

```
DataCloneError: The object could not be cloned.
```

I've dug around other devtools, this is how ember-inspector fixed it https://github.com/emberjs/ember-inspector/commit/5fb7299a34cbf75921d390e5f1ea08d2af735bee

**Comment by HugoDF** [comment]
I've got a fix for this, it's some issue with Proxy unfurling/serialisation/cloning.

It might be an underlying issue with Alpine getUnobservedData though

**Comment by HugoDF** [comment]
This is fixed in master, can track the progress on the milestone 😄 to see when 0.0.3 gets released.
